[project]
name = "timetableforwarder"
version = "0.1.0"
description = "Timetable forwarder from NGAEK"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "alembic>=1.16.5",
    "asyncpg>=0.30.0",
    "dishka>=1.6.0",
    "httpx>=0.28.1",
    "sqlalchemy>=2.0.43",
    "tomli>=2.0.1",
    "tomli-w>=1.2.0",
]

[dependency-groups]
dev = [
    "numpy>=2.3.3",
    "ocrspace>=2.3.0",
    "opencv-python>=4.11.0.86",
    "requests>=2.32.5",
]
