"""update tables

Revision ID: 3501875f2bad
Revises: 8554d742cc17
Create Date: 2025-09-10 09:47:03.292359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3501875f2bad'
down_revision: Union[str, Sequence[str], None] = '8554d742cc17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribed_groups', sa.String(), nullable=True))
    op.drop_column('users', 'subscribed_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribed_group', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'subscribed_groups')
    # ### end Alembic commands ###
