"""create subscribed_groups table

Revision ID: 8554d742cc17
Revises: 344ff08446bf
Create Date: 2025-09-09 22:28:48.127063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8554d742cc17'
down_revision: Union[str, Sequence[str], None] = '344ff08446bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribed_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('subscribed_group', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribed_groups_group_id'), 'subscribed_groups', ['group_id'], unique=True)
    op.drop_column('users', 'is_subscribed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_subscribed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subscribed_groups_group_id'), table_name='subscribed_groups')
    op.drop_table('subscribed_groups')
    # ### end Alembic commands ###
